import DefaultTheme from 'vitepress/theme';
import type { Theme } from 'vitepress';
import './custom.scss';
import BarChartDemo from '../components/BarChartDemo.vue';
import ResponsiveBarChartDemo from '../components/ResponsiveBarChartDemo.vue';
import LineChartDemo from '../components/LineChartDemo.vue';
import MultilineChartDemo from '../components/MultilineChartDemo.vue';
import StackedColumnsDemo from '../components/StackedColumnsDemo.vue';
import AreaChartDemo from '../components/AreaChartDemo.vue';
import ScatterplotDemo from '../components/ScatterplotDemo.vue';
import HistogramDemo from '../components/HistogramDemo.vue';
import HorizontalBarChartDemo from '../components/HorizontalBarChartDemo.vue';
import DonutChartDemo from '../components/DonutChartDemo.vue';
import StackedAreaDemo from '../components/StackedAreaDemo.vue';
import LollipopDemo from '../components/LollipopDemo.vue';
import DivergingBarDemo from '../components/DivergingBarDemo.vue';
import SlopeChartDemo from '../components/SlopeChartDemo.vue';
import AlluvialDemo from '../components/AlluvialDemo.vue';
import ArcDiagramDemo from '../components/ArcDiagramDemo.vue';
import TransformingChartDemo from '../components/TransformingChartDemo.vue';
import GuideFirstChartDemo from '../components/GuideFirstChartDemo.vue';
import GuideLifecycleDemo from '../components/GuideLifecycleDemo.vue';
import GuideLayersDemo from '../components/GuideLayersDemo.vue';
import GuideConfigDemo from '../components/GuideConfigDemo.vue';
import GuideEventsDemo from '../components/GuideEventsDemo.vue';
import GuideAttachmentsDemo from '../components/GuideAttachmentsDemo.vue';
import RoundedBarChartDemo from '../components/RoundedBarChartDemo.vue';
import StepLineChartDemo from '../components/StepLineChartDemo.vue';
import BarLineComboDemo from '../components/BarLineComboDemo.vue';
import SortedBarChartDemo from '../components/SortedBarChartDemo.vue';
import GroupedBarChartDemo from '../components/GroupedBarChartDemo.vue';
import StackedBarLineDemo from '../components/StackedBarLineDemo.vue';
import ScatterTrendLineDemo from '../components/ScatterTrendLineDemo.vue';
import HistogramDensityDemo from '../components/HistogramDensityDemo.vue';
import LollipopAreaRangeDemo from '../components/LollipopAreaRangeDemo.vue';
import DivergingLollipopDemo from '../components/DivergingLollipopDemo.vue';
import DualAxisChartDemo from '../components/DualAxisChartDemo.vue';
import AreaBarOverlayDemo from '../components/AreaBarOverlayDemo.vue';
import SparklineGridDemo from '../components/SparklineGridDemo.vue';
import ConfidenceBandDemo from '../components/ConfidenceBandDemo.vue';
import MovingAverageDemo from '../components/MovingAverageDemo.vue';
import GradientAreaDemo from '../components/GradientAreaDemo.vue';
import BumpChartDemo from '../components/BumpChartDemo.vue';
import NormalizedChartDemo from '../components/NormalizedChartDemo.vue';
import AnnotatedLineDemo from '../components/AnnotatedLineDemo.vue';
import ConnectedScatterDemo from '../components/ConnectedScatterDemo.vue';
import BubbleChartDemo from '../components/BubbleChartDemo.vue';
import LabeledBubbleChartDemo from '../components/LabeledBubbleChartDemo.vue';
import HomeGallery from '../components/HomeGallery.vue';
import HomeWhySection from '../components/HomeWhySection.vue';

export default {
  extends: DefaultTheme,
  enhanceApp({ app }) {
    app.component('BarChartDemo', BarChartDemo);
    app.component('ResponsiveBarChartDemo', ResponsiveBarChartDemo);
    app.component('LineChartDemo', LineChartDemo);
    app.component('MultilineChartDemo', MultilineChartDemo);
    app.component('StackedColumnsDemo', StackedColumnsDemo);
    app.component('AreaChartDemo', AreaChartDemo);
    app.component('ScatterplotDemo', ScatterplotDemo);
    app.component('HistogramDemo', HistogramDemo);
    app.component('HorizontalBarChartDemo', HorizontalBarChartDemo);
    app.component('DonutChartDemo', DonutChartDemo);
    app.component('StackedAreaDemo', StackedAreaDemo);
    app.component('LollipopDemo', LollipopDemo);
    app.component('DivergingBarDemo', DivergingBarDemo);
    app.component('SlopeChartDemo', SlopeChartDemo);
    app.component('AlluvialDemo', AlluvialDemo);
    app.component('ArcDiagramDemo', ArcDiagramDemo);
    app.component('TransformingChartDemo', TransformingChartDemo);
    app.component('GuideFirstChartDemo', GuideFirstChartDemo);
    app.component('GuideLifecycleDemo', GuideLifecycleDemo);
    app.component('GuideLayersDemo', GuideLayersDemo);
    app.component('GuideConfigDemo', GuideConfigDemo);
    app.component('GuideEventsDemo', GuideEventsDemo);
    app.component('GuideAttachmentsDemo', GuideAttachmentsDemo);
    app.component('RoundedBarChartDemo', RoundedBarChartDemo);
    app.component('StepLineChartDemo', StepLineChartDemo);
    app.component('BarLineComboDemo', BarLineComboDemo);
    app.component('SortedBarChartDemo', SortedBarChartDemo);
    app.component('GroupedBarChartDemo', GroupedBarChartDemo);
    app.component('StackedBarLineDemo', StackedBarLineDemo);
    app.component('ScatterTrendLineDemo', ScatterTrendLineDemo);
    app.component('HistogramDensityDemo', HistogramDensityDemo);
    app.component('LollipopAreaRangeDemo', LollipopAreaRangeDemo);
    app.component('DivergingLollipopDemo', DivergingLollipopDemo);
    app.component('DualAxisChartDemo', DualAxisChartDemo);
    app.component('AreaBarOverlayDemo', AreaBarOverlayDemo);
    app.component('SparklineGridDemo', SparklineGridDemo);
    app.component('ConfidenceBandDemo', ConfidenceBandDemo);
    app.component('MovingAverageDemo', MovingAverageDemo);
    app.component('GradientAreaDemo', GradientAreaDemo);
    app.component('BumpChartDemo', BumpChartDemo);
    app.component('NormalizedChartDemo', NormalizedChartDemo);
    app.component('AnnotatedLineDemo', AnnotatedLineDemo);
    app.component('ConnectedScatterDemo', ConnectedScatterDemo);
    app.component('BubbleChartDemo', BubbleChartDemo);
    app.component('LabeledBubbleChartDemo', LabeledBubbleChartDemo);
    app.component('HomeGallery', HomeGallery);
    app.component('HomeWhySection', HomeWhySection);
  },
} satisfies Theme;
